name: Azure Python 3.5
# on every push
on: [push]
jobs:
  build:
  #on which container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.5.10
    - name: Install dependencies
      run: |
        make install
    # Remove Pylint for now
    # - name: Lint with Pylint
    #   run: |
    #     make lint
    - name: Test with Pytest
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
